### ISSUE TITLE
Fuzzy filtering ("stone" -> "cobblestone")

### ISSUE THREAD

**Issue by redactedscribe** [shurik204/better-suggestions#10]
Similar to [Suggestion Tweaker](https://modrinth.com/mod/suggestion-tweaker): Be able to search "stone" and be returned "cobblestone". Not sure how useful the 4 different filter modes of Suggestion Tweaker are, but fuzzy finding for CLIs only have the one mode and that seems to work well enough.

Thanks!

**Comment by shurik204** [comment]
While I know that this feature would be useful, I don't see a point in reimplementing Suggestion Tweaker in my mod. If you want to have this functionality, just install Suggestion Tweaker alongside my mod.

**Comment by redactedscribe** [comment]
On the surface, it looked like they were different mods aiming to achieve the same things. I'll have to take a closer look, but thanks for letting me know.
