### ISSUE TITLE
[Crash] Game crashes with create mod when trying to type in schedule

### ISSUE THREAD

**Issue by HB-Stratos** [shurik204/better-suggestions#14]
As the title says, create train schedules are unusable with the mod installed

**How to reproduce:**
- install create and better suggestions
- create a world
- acquire a train schedule
- open the menu
- click "add a new action"
- click on the text field to enter a target
![2024-05-18_11 58 26](https://github.com/shurik204/better-suggestions/assets/56313836/c9a24e9e-04a3-49f8-be89-efde1075c92a)

- the game crashes
this does not happen with bettersuggestions removed

[AJ6wr4o.txt](https://github.com/shurik204/better-suggestions/files/15362600/AJ6wr4o.txt) and here's a log from a minimal install

If there's a fix for this, I would appreciate a backport of the changes to 1.20.1 as my server and modpack are unfortunately stuck there for quite a while longer. Thanks!

**Comment by shurik204** [comment]
Modrinth release: https://modrinth.com/mod/better-suggestions/version/ITc4fFDw

**Comment by HB-Stratos** [comment]
Awesome, thank you! Can confirm the bug appears fixed on my end.
