### ISSUE TITLE
Game crashes if do nothing or press Shift when choosing selector in a server

### ISSUE THREAD

**Issue by command-music** [shurik204/better-suggestions#4]
I am using Better Suggestions mod with Quilt Loader and Fabric API, using **Minecraft version 1.20.1**.

What I mean *need to add a selector* is...
`/execute as [HERE]`, `/kill [HERE]`, `/give [HERE]`, etc.

## Situation 1 (Quilt Loader 0.19.2)
When I enter a server and use commands, the game will crash when I **need to add a selector**.
This happens when the following mods are installed:
```
better-suggestions-1.20.1-1.1.0.jar
cloth-config-11.1.106-fabric.jar
qfapi-7.1.2_qsl-6.1.1_fapi-0.87.0_mc-1.20.1.jar
```

## Situation 2 (Quilt Loader 0.19.2)
When I enter a server and use commands, the game will crash if I **press the Shift key** when I need to add a selector.
I have tested that this is not related to sneak or other key binds using the Shift key.
This happens when the following mods are installed:
<details><summary>Situation 2 Mod List</summary>
<p>
```
3dskinlayers-fabric-1.5.4-mc1.20.1.jar
AdvancementPlaques-1.20.1-fabric-1.4.11.jar
animatica-0.6+1.20.jar
appleskin-fabric-mc1.20-2.5.0.jar
architectury-9.1.12-fabric.jar
balm-fabric-1.20-7.0.7.jar
better-suggestions-1.20.1-1.1.0.jar
bettercommandblockui-0.4.2-1.20.jar
BetterF3-7.0.1-Fabric-1.20.1.jar
BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
blur-3.1.0.jar
Bookshelf-Fabric-1.20.1-20.0.2.jar
cave_dust-1.4.1.jar
clientcommands-2.8.3.jar
cloth-config-11.1.106-fabric.jar
continuity-3.0.0-beta.3+1.20.1.jar
DCCH-2.0+1.17.jar
Debugify-1.20.1+2.0.jar
dynamic-fps-2.4.0.jar
EnchantmentDescriptions-Fabric-1.20.1-17.0.3.jar
enhancedblockentities-0.9+1.20.jar
entity_texture_features_fabric_1.20-4.5.0.jar
entityculling-fabric-1.6.2-mc1.20.jar
Essential-fabric_1-19.jar
fabric-carpet-1.20-1.4.112+v230608.jar
fabric-language-kotlin-1.10.8+kotlin.1.9.0.jar
fabricskyboxes-0.7.2+mc1.20.1.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
Iceberg-1.20.1-fabric-1.1.15.jar
indium-1.0.24+mc1.20.1.jar
inspecio-1.8.1+1.20.jar
iris-mc1.20.1-1.6.7.jar
Jade-1.20-fabric-11.5.0.jar
konkrete_fabric_1.6.1_MC_1.20.jar
krypton-0.2.3.jar
lambdabettergrass-1.5.2+1.20.1.jar
lambdynamiclights-2.3.1+1.20.1.jar
language-reload-1.5.8+1.20.1.jar
lazydfu-0.1.3.jar
LegendaryTooltips-1.20.1-fabric-1.4.4.jar
litematica-fabric-1.20.1-0.15.3.jar
lithium-fabric-mc1.20.1-0.11.2.jar
macos-input-fixes-1.5.jar
malilib-fabric-1.20.1-0.16.1.jar
memoryleakfix-fabric-1.17+-1.1.1.jar
minihud-fabric-1.20.1-0.27.0.jar
mixintrace-1.1.1+1.17.jar
modmenu-7.2.1.jar
mousewheelie-1.12.2+mc1.20.1.jar
Neat-1.20-35-FABRIC.jar
ok_zoomer-5.0.0-beta.12+1.20.jar
optigui-2.1.5.jar
PresenceFootsteps-1.9.0.jar
Prism-1.20.1-fabric-1.0.5.jar
puzzle-1.5.2+1.20.jar
qfapi-7.1.2_qsl-6.1.1_fapi-0.87.0_mc-1.20.1.jar
quilt_loading_screen-6.0.0+1.20.1.jar
reeses_sodium_options-1.6.4+mc1.20.1-build.94.jar
replaymod-1.20.1-2.6.13.jar
RoughlyEnoughItems-12.0.645.jar
RoughlyEnoughProfessions-fabric-1.20.1-2.0.1.jar
rpmtw-platform-mod-1.20-1.5.8-quilt.jar
signtools-fabric.1.20.1-1.0.3.jar
sit-1.20-24.jar
sodium-extra-0.5.1+mc1.20.1-build.112.jar
sodium-fabric-mc1.20.1-0.5.1.jar
sodium-shadowy-path-blocks-3.2.0.jar
soundphysics-fabric-1.20.1-1.1.2.jar
symbol-chat-1.20.1-1.1.2.jar
tooltipfix-1.1.1-1.20.jar
tweakeroo-fabric-1.20.1-0.17.1.jar
visible-barriers-2.0.8.jar
visuality-0.7.0+1.20.jar
worldedit-mod-7.2.15.jar
Xaeros_Minimap_23.6.2_Fabric_1.20.jar
XaerosWorldMap_1.33.0_Fabric_1.20.jar
```
</p>
</details> 

## Situation 3 (Fabric Loader 0.14.22)
I also tested with Fabric loader.
However, it also crashes as same as **Situation 1**.
This happens when the following mods are installed:
```
better-suggestions-1.20.1-1.1.0.jar
cloth-config-11.1.106-fabric.jar
fabric-api-0.87.0+1.20.1.jar
```

# Crash Reports and Logs

## Situation 1
[crash-2023-08-16_19.28.35-client.txt](https://github.com/shurik204/better-suggestions/files/12358978/crash-2023-08-16_19.28.35-client.txt)
[2023-08-16-2.log.gz](https://github.com/shurik204/better-suggestions/files/12358989/2023-08-16-2.log.gz)

## Situation 2
[crash-2023-08-16_19.34.32-client.txt](https://github.com/shurik204/better-suggestions/files/12359016/crash-2023-08-16_19.34.32-client.txt)
[2023-08-16-7.log.gz](https://github.com/shurik204/better-suggestions/files/12359008/2023-08-16-7.log.gz)

## Situation 3
[crash-2023-08-16_19.40.26-client.txt](https://github.com/shurik204/better-suggestions/files/12358996/crash-2023-08-16_19.40.26-client.txt)
[2023-08-16-3.log.gz](https://github.com/shurik204/better-suggestions/files/12358994/2023-08-16-3.log.gz)

**Comment by shurik204** [comment]
Thanks for making this issue. The crash was caused by this mod trying to get entity tag list on a server without this mod installed. I've added a fallback for fetching tags on vanilla servers.
