### ISSUE TITLE
Crash with Figura Mod

### ISSUE THREAD

**Issue by Jakeplays12** [shurik204/better-suggestions#8]
When pressing tab while having the[ Figura mod](https://github.com/FiguraMC/Figura) the game crashes with the following error:
https://pastebin.com/FgcZX44J

**Comment by shurik204** [comment]
What Minecraft version are you using? What loader (Fabric or Quilt)? Better Suggestions mod version, Figura mod version? Do you have any other mods installed?

**Comment by Jakeplays12** [comment]
Im using Minecraft 1.20.1 with Fabric (0.14.24) with the following mods

- Better Suggestions (1.2.0)
- Cloth Config (11.1.106)
- Fabric API (0.90.7)
- Figura (0.1.2)
- Mod Menu (7.2.2)
- Sodium (0.5.3)

If theres any more infomation you need please let me know!

**Comment by shurik204** [comment]
Should be fixed in 1.2.2.
